apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 0gainode
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # 로컬 파일 시스템 사용 (ArgoCD가 접근 가능한 경우)
    path: /root/0gnft/k8s
    directory:
      recurse: true
      # 또는 직접 파일 지정
      # files:
      #   - deployment.yaml
      #   - ingress.yaml
      #   - secret-tls.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
